version: "3.8"

services:
  dbpostgres:
    image: postgres:12.17
    container_name: dbpostgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=homebanking
    ports:
      - 6000:5432
    logging:
      driver: none

  backend:
    container_name: backend
    depends_on:
      - dbpostgres
    links:
      - dbpostgres
    build: ./backend
    environment:
      - DB_NAME=homebanking
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_LOCAL_PORT=5432
      - DB_HOST=dbpostgres
    ports:
      - 3001:3001

  frontend:
    container_name: frontend
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend
    environment:
      - BACKEND_URL=backend:3001